"""
MCP generator: emits a runnable Python MCP server from a feature_spec.json.

Strategy: deterministic codegen, NOT an LLM call. The feature spec already
went through Claude in the analyzer — we don't want a second LLM pass to
re-interpret it and possibly drift. So this is a straight template fill.

Each feature in the spec becomes one MCP tool. The tool handler does an
HTTP request to the recorded endpoint, substituting any path/query/body
parameters from the tool input.

Auth model:
  - `cookie`:  the user runs `auth_capture.py` once, which dumps cookies.
               The generated server reads them at startup.
  - `bearer`:  the user sets MCP_AUTH_TOKEN in env.
  - `none`:    no auth.

Output is a single self-contained server.py + a requirements.txt + a README.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from textwrap import indent


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def _safe_id(s: str) -> str:
    """Make a string usable as a Python identifier."""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", s)
    if s and s[0].isdigit():
        s = "_" + s
    return s or "feature"


def _extract_path_params(url_template: str) -> list[str]:
    return re.findall(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", url_template)


def _build_input_schema(feature: dict) -> dict:
    """Turn a feature's endpoint description into an MCP tool input schema."""
    properties: dict = {}
    required: list[str] = []

    endpoint = feature.get("endpoint") or {}
    url_t = endpoint.get("url_template", "")

    # Path params — always required
    for p in _extract_path_params(url_t):
        properties[p] = {"type": "string", "description": f"Path parameter `{p}`"}
        required.append(p)

    # Query params
    for q in endpoint.get("query_params") or []:
        name = q.get("name")
        if not name or name in properties:
            continue
        properties[name] = {
            "type": q.get("type", "string"),
            "description": f"Query parameter `{name}`",
        }
        if q.get("required"):
            required.append(name)

    # Body schema — flatten one level so each top-level body field becomes
    # a tool parameter. Anything deeper, we expose as a generic `body` object.
    body_schema = endpoint.get("body_schema")
    if isinstance(body_schema, dict) and body_schema.get("type") == "object":
        body_props = body_schema.get("properties", {}) or {}
        body_required = set(body_schema.get("required", []) or [])
        for name, sub in body_props.items():
            if name in properties:
                continue  # don't shadow path/query params
            properties[name] = sub if isinstance(sub, dict) else {"type": "string"}
            if name in body_required:
                required.append(name)

    return {
        "type": "object",
        "properties": properties,
        "required": sorted(set(required)),
    }


# --------------------------------------------------------------------------- #
# Server template
# --------------------------------------------------------------------------- #

SERVER_TEMPLATE = '''"""
Auto-generated MCP server for {product_name}.
Generated by auto-mcp from a feature spec.

Run:
    pip install -r requirements.txt
    python server.py

Auth: {auth_type}
{auth_notes}
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP


BASE_URL = {base_url!r}
COOKIES_FILE = Path(os.environ.get("MCP_COOKIES_FILE", "cookies.json"))
BEARER_TOKEN = os.environ.get("MCP_AUTH_TOKEN")


def _load_cookies() -> dict:
    if COOKIES_FILE.exists():
        return json.loads(COOKIES_FILE.read_text())
    return {{}}


def _client() -> httpx.Client:
    headers = {{"User-Agent": "auto-mcp/0.1"}}
    if BEARER_TOKEN:
        headers["Authorization"] = f"Bearer {{BEARER_TOKEN}}"
    return httpx.Client(
        cookies=_load_cookies(),
        headers=headers,
        timeout=30.0,
        follow_redirects=True,
    )


def _fill_template(template: str, args: dict) -> str:
    def repl(m):
        key = m.group(1)
        if key not in args:
            raise ValueError(f"Missing path parameter: {{key}}")
        return str(args[key])
    return re.sub(r"\\{{([a-zA-Z_][a-zA-Z0-9_]*)\\}}", repl, template)


mcp = FastMCP({product_name!r})

{tool_definitions}


if __name__ == "__main__":
    mcp.run()
'''


TOOL_TEMPLATE = '''@mcp.tool()
def {fn_name}(args: dict) -> str:
    """{description}

    Input schema (JSON):
{schema_doc}

    Returns: {returns}
    """
    method = {method!r}
    url_template = {url_template!r}

    path_params = {path_params!r}
    query_param_names = {query_param_names!r}
    body_param_names = {body_param_names!r}

    # Validate required
    for r in {required!r}:
        if r not in args:
            return f"Error: missing required parameter `{{r}}`"

    url = _fill_template(url_template, args)
    params = {{k: args[k] for k in query_param_names if k in args}}
    body = {{k: args[k] for k in body_param_names if k in args}} or None

    with _client() as client:
        try:
            resp = client.request(method, url, params=params, json=body)
        except httpx.HTTPError as e:
            return f"Network error: {{e}}"

    text = resp.text
    if len(text) > 8000:
        text = text[:8000] + f"... [truncated, {{len(resp.text)}} bytes total]"
    return f"HTTP {{resp.status_code}}\\n\\n{{text}}"
'''

DIRECT_TOOL_TEMPLATE = '''@mcp.tool()
def {fn_name}(args: dict) -> str:
    """{description}

    Input schema (JSON):
{schema_doc}

    Returns: {returns}
    """
    # Validate required
    for r in {required!r}:
        if r not in args:
            return f"Error: missing required parameter `{{r}}`"

    try:
{code_body}
    except Exception as e:
        return f"Error: {{e}}"
'''


def render_direct_tool(feature: dict) -> str:
    """Render a tool whose implementation comes directly from source code."""
    schema = _build_input_schema(feature)
    schema_doc = indent(json.dumps(schema, indent=2), "        ")
    raw_body = feature.get("code_snippet", "        return 'Not implemented'")
    # Ensure every line is indented by 8 spaces (inside try block)
    body_lines = [
        "        " + line if not line.startswith("        ") else line
        for line in raw_body.splitlines()
    ]
    code_body = "\n".join(body_lines) or "        return 'Not implemented'"
    return DIRECT_TOOL_TEMPLATE.format(
        fn_name=_safe_id(feature["id"]),
        description=feature.get("description", "").replace('"""', "'''"),
        schema_doc=schema_doc,
        returns=feature.get("returns", "Result of the operation."),
        required=schema["required"],
        code_body=code_body,
    )


def render_tool(feature: dict) -> str:
    impl_type = feature.get("implementation_type", "")
    if impl_type in ("direct_code", "reconstructed") and feature.get("code_snippet"):
        return render_direct_tool(feature)

    endpoint = feature.get("endpoint") or {}
    schema = _build_input_schema(feature)
    url_t = endpoint.get("url_template", "")
    path_params = _extract_path_params(url_t)
    query_params = [q["name"] for q in (endpoint.get("query_params") or []) if q.get("name")]
    body_props = []
    bs = endpoint.get("body_schema")
    if isinstance(bs, dict) and isinstance(bs.get("properties"), dict):
        body_props = list(bs["properties"].keys())

    schema_doc = indent(json.dumps(schema, indent=2), "        ")

    return TOOL_TEMPLATE.format(
        fn_name=_safe_id(feature["id"]),
        description=feature.get("description", "").replace('"""', "'''"),
        schema_doc=schema_doc,
        returns=feature.get("returns", "Raw HTTP response body."),
        method=endpoint.get("method", "GET"),
        url_template=url_t,
        path_params=path_params,
        query_param_names=query_params,
        body_param_names=body_props,
        required=schema["required"],
    )


REQUIREMENTS_BY_IMPORT = {
    "psycopg2": "psycopg2-binary>=2.9.0",
    "mysql.connector": "mysql-connector-python>=8.0.0",
    "pymongo": "pymongo>=4.0.0",
    "supabase": "supabase>=2.0.0",
    "openai": "openai>=1.35.0",
    "anthropic": "anthropic>=0.29.0",
    "google.generativeai": "google-generativeai>=0.7.0",
    "cohere": "cohere>=5.0.0",
    "boto3": "boto3>=1.34.0",
    "google.cloud.storage": "google-cloud-storage>=2.0.0",
    "firebase_admin": "firebase-admin>=6.0.0",
    "jose": "python-jose[cryptography]>=3.3.0",
    "redis": "redis>=5.0.0",
    "sqlalchemy": "sqlalchemy>=2.0.0",
}


def _extract_package(import_line: str) -> str:
    """Extract the top-level package name from an import statement."""
    line = import_line.strip()
    if line.startswith("from "):
        return line.split()[1].split(".")[0]
    if line.startswith("import "):
        return line.split()[1].split(".")[0].split(",")[0].strip()
    return ""


def _collect_requirements(spec: dict) -> list[str]:
    """Build a dynamic requirements.txt from what the features actually import."""
    reqs: set[str] = {"mcp>=1.0.0", "httpx>=0.27.0"}
    for feature in spec.get("features", []):
        for imp_line in feature.get("code_imports") or []:
            pkg = _extract_package(imp_line)
            if pkg and pkg in REQUIREMENTS_BY_IMPORT:
                reqs.add(REQUIREMENTS_BY_IMPORT[pkg])
    return sorted(reqs)


def generate(spec: dict, out_dir: str | Path, user_env: dict | None = None) -> None:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    auth = spec.get("auth", {}) or {}
    auth_type = auth.get("type", "none")
    auth_notes = auth.get("notes", "")

    # Collect extra imports declared by direct_code features
    extra_imports: list[str] = []
    seen_imports: set[str] = set()
    for f in spec.get("features", []):
        if f.get("implementation_type") == "direct_code":
            for imp in f.get("code_imports") or []:
                if imp and imp not in seen_imports:
                    seen_imports.add(imp)
                    extra_imports.append(imp)

    tools = "\n\n".join(render_tool(f) for f in spec.get("features", []))

    extra_imports_block = ("\n".join(extra_imports) + "\n\n") if extra_imports else ""
    server_code = SERVER_TEMPLATE.format(
        product_name=spec.get("product_name", "auto-mcp"),
        base_url=spec.get("base_url", ""),
        auth_type=auth_type,
        auth_notes=auth_notes,
        tool_definitions=tools,
    )
    # Inject extra imports right after the built-in imports block
    if extra_imports_block:
        server_code = server_code.replace(
            "import httpx\nfrom mcp.server.fastmcp import FastMCP",
            "import httpx\nfrom mcp.server.fastmcp import FastMCP\n\n" + extra_imports_block.rstrip(),
        )

    (out_dir / "server.py").write_text(server_code)
    (out_dir / "requirements.txt").write_text("\n".join(_collect_requirements(spec)) + "\n")

    # Write .env.example with detected env vars (values omitted for security)
    env_vars = spec.get("env_vars") or []
    if env_vars:
        env_example_lines = [
            f"# {v.get('description', '')}\n"
            f"{'# (required)' if v.get('required') else '# (optional)'}\n"
            f"{v['name']}=\n"
            for v in env_vars
        ]
        (out_dir / ".env.example").write_text("\n".join(env_example_lines))
    # Write .env with user-provided values (never committed — listed in gitignore)
    if user_env:
        env_lines = [f"{k}={v}" for k, v in user_env.items() if v]
        if env_lines:
            (out_dir / ".env").write_text("\n".join(env_lines) + "\n")
    # .gitignore so the .env never gets committed
    (out_dir / ".gitignore").write_text(".env\n")

    readme = f"""# Auto-generated MCP server for {spec.get('product_name', '')}

Generated by auto-mcp.

## Setup

```bash
pip install -r requirements.txt
```

Auth type: **{auth_type}**

{auth_notes}

For cookie auth, run the helper `auth_capture.py` (in the auto-mcp repo)
once against the target site and place the resulting `cookies.json` next
to `server.py`.

For bearer auth, set:

```bash
export MCP_AUTH_TOKEN=<your-token>
```

## Run

```bash
python server.py
```

Then add this server to your MCP-aware client (Claude Desktop, etc.) by
pointing it at the script.

## Tools generated

{chr(10).join(f"- `{f['id']}` — {f.get('description', '').splitlines()[0] if f.get('description') else ''}" for f in spec.get('features', []))}
"""
    (out_dir / "README.md").write_text(readme)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("spec", help="Path to feature_spec.json")
    parser.add_argument("--out", default="generated_mcp")
    args = parser.parse_args()
    spec = json.loads(Path(args.spec).read_text())
    generate(spec, args.out)
    print(f"Wrote MCP server to {args.out}/")
