"""
Auto-generated MCP server for demo-blog.
Generated by auto-mcp from a feature spec.

Run:
    pip install -r requirements.txt
    python server.py

Auth: bearer
Requires a personal access token. Set MCP_AUTH_TOKEN.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP


BASE_URL = 'https://api.demo-blog.example'
COOKIES_FILE = Path(os.environ.get("MCP_COOKIES_FILE", "cookies.json"))
BEARER_TOKEN = os.environ.get("MCP_AUTH_TOKEN")


def _load_cookies() -> dict:
    if COOKIES_FILE.exists():
        return json.loads(COOKIES_FILE.read_text())
    return {}


def _client() -> httpx.Client:
    headers = {"User-Agent": "auto-mcp/0.1"}
    if BEARER_TOKEN:
        headers["Authorization"] = f"Bearer {BEARER_TOKEN}"
    return httpx.Client(
        cookies=_load_cookies(),
        headers=headers,
        timeout=30.0,
        follow_redirects=True,
    )


def _fill_template(template: str, args: dict) -> str:
    def repl(m):
        key = m.group(1)
        if key not in args:
            raise ValueError(f"Missing path parameter: {key}")
        return str(args[key])
    return re.sub(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}", repl, template)


mcp = FastMCP('demo-blog')

@mcp.tool()
def list_posts(args: dict) -> str:
    """Get a paginated list of all blog posts.

    Input schema (JSON):
        {
          "type": "object",
          "properties": {
            "page": {
              "type": "integer",
              "description": "Query parameter `page`"
            },
            "tag": {
              "type": "string",
              "description": "Query parameter `tag`"
            }
          },
          "required": []
        }

    Returns: JSON array of post objects with id, title, excerpt, author.
    """
    method = 'GET'
    url_template = 'https://api.demo-blog.example/v1/posts'

    path_params = []
    query_param_names = ['page', 'tag']
    body_param_names = []

    # Validate required
    for r in []:
        if r not in args:
            return f"Error: missing required parameter `{r}`"

    url = _fill_template(url_template, args)
    params = {k: args[k] for k in query_param_names if k in args}
    body = {k: args[k] for k in body_param_names if k in args} or None

    with _client() as client:
        try:
            resp = client.request(method, url, params=params, json=body)
        except httpx.HTTPError as e:
            return f"Network error: {e}"

    text = resp.text
    if len(text) > 8000:
        text = text[:8000] + f"... [truncated, {len(resp.text)} bytes total]"
    return f"HTTP {resp.status_code}\n\n{text}"


@mcp.tool()
def get_post(args: dict) -> str:
    """Fetch the full content of a specific post by ID.

    Input schema (JSON):
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Path parameter `id`"
            }
          },
          "required": [
            "id"
          ]
        }

    Returns: JSON object with full post including body markdown.
    """
    method = 'GET'
    url_template = 'https://api.demo-blog.example/v1/posts/{id}'

    path_params = ['id']
    query_param_names = []
    body_param_names = []

    # Validate required
    for r in ['id']:
        if r not in args:
            return f"Error: missing required parameter `{r}`"

    url = _fill_template(url_template, args)
    params = {k: args[k] for k in query_param_names if k in args}
    body = {k: args[k] for k in body_param_names if k in args} or None

    with _client() as client:
        try:
            resp = client.request(method, url, params=params, json=body)
        except httpx.HTTPError as e:
            return f"Network error: {e}"

    text = resp.text
    if len(text) > 8000:
        text = text[:8000] + f"... [truncated, {len(resp.text)} bytes total]"
    return f"HTTP {resp.status_code}\n\n{text}"


@mcp.tool()
def create_post(args: dict) -> str:
    """Publish a new blog post.

    Input schema (JSON):
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "body": {
              "type": "string"
            },
            "tags": {
              "type": "array"
            }
          },
          "required": [
            "body",
            "title"
          ]
        }

    Returns: JSON object with the newly created post.
    """
    method = 'POST'
    url_template = 'https://api.demo-blog.example/v1/posts'

    path_params = []
    query_param_names = []
    body_param_names = ['title', 'body', 'tags']

    # Validate required
    for r in ['body', 'title']:
        if r not in args:
            return f"Error: missing required parameter `{r}`"

    url = _fill_template(url_template, args)
    params = {k: args[k] for k in query_param_names if k in args}
    body = {k: args[k] for k in body_param_names if k in args} or None

    with _client() as client:
        try:
            resp = client.request(method, url, params=params, json=body)
        except httpx.HTTPError as e:
            return f"Network error: {e}"

    text = resp.text
    if len(text) > 8000:
        text = text[:8000] + f"... [truncated, {len(resp.text)} bytes total]"
    return f"HTTP {resp.status_code}\n\n{text}"



if __name__ == "__main__":
    mcp.run()
